//! Session data types for JSONL persistence.
//!
//! Mirrors the TS types from:
//! - packages/agent/src/harness/session/jsonl-storage.ts
//! - packages/coding-agent/src/core/session-manager.ts
//!
//! A session is stored as an append-only JSONL file where the first line is a
//! `SessionHeader` and subsequent lines are `SessionEntry` values. Entries form
//! a tree via `id`/`parent_id` pointers. The "leaf" tracks the current position;
//! appending creates a child of the current leaf; branching moves the leaf to a
//! different node.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

// Re-export pi-ai-core Message for session context.
pub use pi_ai_core::types::Message;

/// Unique session entry identifier.
pub type EntryId = String;

/// Error type for session operations.
#[derive(Debug, thiserror::Error)]
pub enum SessionError {
    /// I/O error (file read/write).
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),

    /// JSON serialization / deserialization error.
    #[error("JSON error: {0}")]
    Json(#[from] serde_json::Error),

    /// The session file is malformed or missing a header.
    #[error("Invalid session file: {0}")]
    InvalidSession(String),

    /// Referenced entry does not exist.
    #[error("Entry {0} not found")]
    EntryNotFound(EntryId),
}

// ---------------------------------------------------------------------------
// Session header
// ---------------------------------------------------------------------------

/// Session header — the first line in a JSONL session file.
///
/// Mirrors `SessionHeader` in the TS `session-manager.ts`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionHeader {
    /// Always `"session"`.
    pub r#type: String,
    /// Session format version; `None` for v1 sessions.
    #[serde(default)]
    pub version: Option<u32>,
    /// Unique session identifier.
    pub id: EntryId,
    /// ISO 8601 timestamp.
    pub timestamp: String,
    /// Working directory when the session was started.
    pub cwd: String,
    /// Path to parent session file (if this session was forked).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent_session: Option<String>,
}

impl SessionHeader {
    /// Create a new v3 session header.
    pub fn new(cwd: impl Into<String>, id: EntryId) -> Self {
        Self {
            r#type: "session".to_string(),
            version: Some(3),
            id,
            timestamp: chrono::Utc::now().to_rfc3339(),
            cwd: cwd.into(),
            parent_session: None,
        }
    }

    /// Create a new v3 session header referencing a parent session.
    pub fn with_parent(cwd: impl Into<String>, id: EntryId, parent_session: impl Into<String>) -> Self {
        Self { parent_session: Some(parent_session.into()), ..Self::new(cwd, id) }
    }
}

// ---------------------------------------------------------------------------
// Session entries
// ---------------------------------------------------------------------------

/// Data common to all session entry types.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionEntryBase {
    /// Unique entry identifier.
    pub id: EntryId,
    /// Parent entry ID, or `None` for root entries.
    pub parent_id: Option<EntryId>,
    /// ISO 8601 timestamp.
    pub timestamp: String,
}

/// A message entry (user, assistant, tool, etc.).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MessageEntryData {
    /// Unique entry identifier.
    pub id: EntryId,
    /// Parent entry ID.
    pub parent_id: Option<EntryId>,
    /// ISO 8601 timestamp.
    pub timestamp: String,
    /// The full AgentMessage JSON.
    pub message: serde_json::Value,
}

/// A compaction entry that summarizes a range of prior messages.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CompactionEntryData {
    /// Unique entry identifier.
    pub id: EntryId,
    /// Parent entry ID.
    pub parent_id: Option<EntryId>,
    /// ISO 8601 timestamp.
    pub timestamp: String,
    /// Human-readable summary of the compacted messages.
    pub summary: String,
    /// The ID of the first entry kept after compaction.
    pub first_kept_entry_id: EntryId,
    /// Number of tokens consumed before compaction.
    pub tokens_before: u64,
    /// Extension-specific data.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
    /// True if generated by an extension hook.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub from_hook: Option<bool>,
}

/// Thinking level change entry.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThinkingLevelChangeEntryData {
    /// Unique entry identifier.
    pub id: EntryId,
    /// Parent entry ID.
    pub parent_id: Option<EntryId>,
    /// ISO 8601 timestamp.
    pub timestamp: String,
    /// The thinking level value.
    pub thinking_level: String,
}

/// Model change entry.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelChangeEntryData {
    /// Unique entry identifier.
    pub id: EntryId,
    /// Parent entry ID.
    pub parent_id: Option<EntryId>,
    /// ISO 8601 timestamp.
    pub timestamp: String,
    /// Provider name.
    pub provider: String,
    /// Model identifier.
    pub model_id: String,
}

/// Branch summary entry — captures context from an abandoned path.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BranchSummaryEntryData {
    /// Unique entry identifier.
    pub id: EntryId,
    /// Parent entry ID.
    pub parent_id: Option<EntryId>,
    /// ISO 8601 timestamp.
    pub timestamp: String,
    /// The entry ID where the branch was created from.
    pub from_id: String,
    /// Summary text of the abandoned conversation.
    pub summary: String,
    /// Extension-specific data.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
    /// True if generated by an extension hook.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub from_hook: Option<bool>,
}

/// Label entry for user-defined bookmarks on entries.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LabelEntryData {
    /// Unique entry identifier.
    pub id: EntryId,
    /// Parent entry ID.
    pub parent_id: Option<EntryId>,
    /// ISO 8601 timestamp.
    pub timestamp: String,
    /// The entry being labelled.
    pub target_id: EntryId,
    /// The label text; `None` or empty clears the label.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

/// Custom entry for extension-specific data (not sent to LLM).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomEntryData {
    /// Unique entry identifier.
    pub id: EntryId,
    /// Parent entry ID.
    pub parent_id: Option<EntryId>,
    /// ISO 8601 timestamp.
    pub timestamp: String,
    /// Extension identifier for filtering on reload.
    pub custom_type: String,
    /// Extension-specific data.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

/// Custom message entry for extension-injected LLM context.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomMessageEntryData {
    /// Unique entry identifier.
    pub id: EntryId,
    /// Parent entry ID.
    pub parent_id: Option<EntryId>,
    /// ISO 8601 timestamp.
    pub timestamp: String,
    /// Extension identifier.
    pub custom_type: String,
    /// Message content (string or content block array).
    pub content: serde_json::Value,
    /// Whether to display in TUI.
    pub display: bool,
    /// Extension-specific metadata (not sent to LLM).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
}

/// Session info entry (e.g., user-defined display name).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionInfoEntryData {
    /// Unique entry identifier.
    pub id: EntryId,
    /// Parent entry ID.
    pub parent_id: Option<EntryId>,
    /// ISO 8601 timestamp.
    pub timestamp: String,
    /// User-defined display name; empty clears the name.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// A single entry in the session tree.
///
/// Each line (after the header) in a JSONL session file is one of these.
/// The `type` field in the JSON discriminates the variant.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum SessionEntry {
    /// A user, assistant, or tool message.
    #[serde(rename = "message")]
    Message(MessageEntryData),
    /// A compaction summary.
    #[serde(rename = "compaction")]
    Compaction(CompactionEntryData),
    /// A thinking level change.
    #[serde(rename = "thinking_level_change")]
    ThinkingLevelChange(ThinkingLevelChangeEntryData),
    /// A model change.
    #[serde(rename = "model_change")]
    ModelChange(ModelChangeEntryData),
    /// A branch summary (context from an abandoned path).
    #[serde(rename = "branch_summary")]
    BranchSummary(BranchSummaryEntryData),
    /// A label / bookmark.
    #[serde(rename = "label")]
    Label(LabelEntryData),
    /// Extension-specific custom data (not sent to LLM).
    #[serde(rename = "custom")]
    Custom(CustomEntryData),
    /// Extension-injected message (sent to LLM).
    #[serde(rename = "custom_message")]
    CustomMessage(CustomMessageEntryData),
    /// Session metadata (display name, etc.).
    #[serde(rename = "session_info")]
    SessionInfo(SessionInfoEntryData),
}

impl SessionEntry {
    /// Returns the entry's unique identifier.
    pub fn id(&self) -> &str {
        match self {
            Self::Message(e) => &e.id,
            Self::Compaction(e) => &e.id,
            Self::ThinkingLevelChange(e) => &e.id,
            Self::ModelChange(e) => &e.id,
            Self::BranchSummary(e) => &e.id,
            Self::Label(e) => &e.id,
            Self::Custom(e) => &e.id,
            Self::CustomMessage(e) => &e.id,
            Self::SessionInfo(e) => &e.id,
        }
    }

    /// Returns the parent entry ID, if any.
    pub fn parent_id(&self) -> Option<&str> {
        match self {
            Self::Message(e) => e.parent_id.as_deref(),
            Self::Compaction(e) => e.parent_id.as_deref(),
            Self::ThinkingLevelChange(e) => e.parent_id.as_deref(),
            Self::ModelChange(e) => e.parent_id.as_deref(),
            Self::BranchSummary(e) => e.parent_id.as_deref(),
            Self::Label(e) => e.parent_id.as_deref(),
            Self::Custom(e) => e.parent_id.as_deref(),
            Self::CustomMessage(e) => e.parent_id.as_deref(),
            Self::SessionInfo(e) => e.parent_id.as_deref(),
        }
    }

    /// Returns the ISO 8601 timestamp string.
    pub fn timestamp(&self) -> &str {
        match self {
            Self::Message(e) => &e.timestamp,
            Self::Compaction(e) => &e.timestamp,
            Self::ThinkingLevelChange(e) => &e.timestamp,
            Self::ModelChange(e) => &e.timestamp,
            Self::BranchSummary(e) => &e.timestamp,
            Self::Label(e) => &e.timestamp,
            Self::Custom(e) => &e.timestamp,
            Self::CustomMessage(e) => &e.timestamp,
            Self::SessionInfo(e) => &e.timestamp,
        }
    }
}

/// A raw file entry — either a header or a session entry.
///
/// Used when parsing the raw lines of a JSONL file where we don't yet know
/// whether a line is the header or a body entry.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FileEntry {
    /// Session header (first line).
    Header(SessionHeader),
    /// Session body entry (subsequent lines).
    Entry(SessionEntry),
}

// ---------------------------------------------------------------------------
// Resolved session context
// ---------------------------------------------------------------------------

/// Resolved conversation context produced by `build_session_context`.
///
/// This is the data that gets sent to the LLM: a flat list of messages with
/// the current thinking level and model.
#[derive(Debug, Clone)]
pub struct SessionContext {
    /// Messages in conversation order.
    pub messages: Vec<Message>,
    /// Current thinking level (defaults to `"off"`).
    pub thinking_level: String,
    /// Current model (provider + model ID).
    pub model: Option<(String, String)>,
}

impl Default for SessionContext {
    fn default() -> Self {
        Self { messages: Vec::new(), thinking_level: "off".to_string(), model: None }
    }
}

// ---------------------------------------------------------------------------
// Tree node for getTree()
// ---------------------------------------------------------------------------

/// A node in the session tree — a defensive copy of the session structure.
#[derive(Debug, Clone)]
pub struct SessionTreeNode {
    /// The entry at this node.
    pub entry: SessionEntry,
    /// Child nodes.
    pub children: Vec<SessionTreeNode>,
    /// Resolved label for this entry, if any.
    pub label: Option<String>,
}

// ---------------------------------------------------------------------------
// Label cache
// ---------------------------------------------------------------------------

/// In-memory cache of resolved labels, keyed by target entry ID.
pub type LabelCache = HashMap<EntryId, String>;

/// Build a label cache from a slice of entries.
pub fn build_label_cache(entries: &[SessionEntry]) -> LabelCache {
    let mut cache = LabelCache::new();
    for entry in entries {
        if let SessionEntry::Label(label) = entry {
            if let Some(ref l) = label.label {
                let trimmed = l.trim();
                if !trimmed.is_empty() {
                    cache.insert(label.target_id.clone(), trimmed.to_string());
                } else {
                    cache.remove(&label.target_id);
                }
            } else {
                cache.remove(&label.target_id);
            }
        }
    }
    cache
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Generate a short entry ID (8 hex characters) with collision checking.
///
/// Mirrors `generateId()` / `generateEntryId()` in the TS source.
pub fn generate_entry_id(existing: &std::collections::HashSet<String>) -> EntryId {
    for _ in 0..100 {
        let id = uuid::Uuid::new_v4().simple().to_string()[..8].to_string();
        if !existing.contains(&id) {
            return id;
        }
    }
    // Fallback to full UUID on extreme collision.
    uuid::Uuid::new_v4().to_string()
}

/// Generate a session ID (full UUID).
///
/// Mirrors `createSessionId()` in the TS source.
pub fn create_session_id() -> EntryId {
    uuid::Uuid::new_v4().to_string()
}

/// Create an ISO 8601 timestamp string for the current moment.
pub fn now_timestamp() -> String {
    chrono::Utc::now().to_rfc3339()
}
